data:extend({
  {
    type = "sprite",
    name = "ee_logo",
    filename = "__EditorExtensions__/graphics/gui/crafting-group.png",
    size = 128,
    mipmap_count = 2,
    flags = { "gui-icon" },
  },
  {
    type = "sprite",
    name = "ee_import_inventory_filters",
    filename = "__EditorExtensions__/graphics/gui/inventory-filters.png",
    y = 0,
    size = 32,
    mipmap_count = 2,
    flags = { "gui-icon" },
  },
  {
    type = "sprite",
    name = "ee_export_inventory_filters",
    filename = "__EditorExtensions__/graphics/gui/inventory-filters.png",
    y = 32,
    size = 32,
    mipmap_count = 2,
    flags = { "gui-icon" },
  },
  {
    type = "sprite",
    name = "ee_open_default_gui_black",
    filename = "__EditorExtensions__/graphics/gui/frame-action-icons.png",
    size = 32,
    flags = { "gui-icon" },
  },
  {
    type = "sprite",
    name = "ee_open_default_gui_white",
    filename = "__EditorExtensions__/graphics/gui/frame-action-icons.png",
    x = 32,
    size = 32,
    flags = { "gui-icon" },
  },
})
